// Generated by scripts/generate-locale-routes.cjs; edit the English implementation.
export { default } from '@/app/(english)/art/early-first-paintings/page';
import { metadataForRoute } from '@/i18n/route-metadata';

export async function generateMetadata({ params }: { params: Record<string, string> }) {
  return metadataForRoute("/art/early-first-paintings", params, 'es');
}
