// Generated by scripts/generate-locale-routes.cjs.
import type { Metadata } from 'next';
import { baseMetadata } from '@/lib/seo';
import { generateMetadata as metadata0 } from '@/app/(english)/[shortSlug]/layout';
import { generateStaticParams as params0 } from '@/app/(english)/[shortSlug]/page';
import { generateMetadata as metadata1 } from '@/app/(english)/art-experiences/events/[id]/layout';
import { generateStaticParams as params1 } from '@/app/(english)/art-experiences/events/[id]/page';
import { metadata as metadata2 } from '@/app/(english)/art-experiences/events/layout';
import { metadata as metadata3 } from '@/app/(english)/art-experiences/layout';
import { metadata as metadata4 } from '@/app/(english)/art-experiences/you-and-i-gallery/layout';
import { generateMetadata as metadata5 } from '@/app/(english)/art/[collection]/[painting]/layout';
import { generateStaticParams as params5 } from '@/app/(english)/art/[collection]/[painting]/page';
import { generateMetadata as metadata6 } from '@/app/(english)/art/[collection]/layout';
import { generateStaticParams as params6 } from '@/app/(english)/art/[collection]/page';
import { metadata as metadata7 } from '@/app/(english)/art/about/page';
import { metadata as metadata8 } from '@/app/(english)/art/all-paintings/layout';
import { metadata as metadata9 } from '@/app/(english)/art/collaborations/layout';
import { metadata as metadata10 } from '@/app/(english)/art/collections/layout';
import { metadata as metadata11 } from '@/app/(english)/art/contact/layout';
import { metadata as metadata12 } from '@/app/(english)/art/early-first-paintings/layout';
import { metadata as metadata13 } from '@/app/(english)/art/page';
import { metadata as metadata14 } from '@/app/(english)/creative-services/art-classes/layout';
import { metadata as metadata15 } from '@/app/(english)/creative-services/brand-identity/layout';
import { metadata as metadata16 } from '@/app/(english)/creative-services/graphic-recording/layout';
import { metadata as metadata17 } from '@/app/(english)/creative-services/layout';
import { metadata as metadata18 } from '@/app/(english)/creative-services/ux-ui-design/layout';
import { metadata as metadata19 } from '@/app/(english)/my-art/blog/layout';
import { metadata as metadata20 } from '@/app/(english)/my-art/digital-art/layout';
import { metadata as metadata21 } from '@/app/(english)/my-art/everyday-photography/layout';
import { metadata as metadata22 } from '@/app/(english)/my-art/traditional-art/layout';
import { metadata as metadata23 } from '@/app/(english)/my-art/wildlife-photography/gallery/layout';
import { metadata as metadata24 } from '@/app/(english)/my-art/wildlife-photography/layout';
import { metadata as metadata26 } from '@/app/(english)/photography/family-maternity/gallery/page';
import { metadata as metadata27 } from '@/app/(english)/photography/family-maternity/layout';
import { metadata as metadata28 } from '@/app/(english)/photography/headshots/gallery/page';
import { metadata as metadata29 } from '@/app/(english)/photography/headshots/page';
import { metadata as metadata30 } from '@/app/(english)/photography/pets/gallery/page';
import { metadata as metadata31 } from '@/app/(english)/photography/pets/layout';
import { metadata as metadata32 } from '@/app/(english)/photography/wedding-couples/gallery/page';
import { metadata as metadata33 } from '@/app/(english)/photography/wedding-couples/layout';
import { metadata as metadata34 } from '@/app/(english)/portfolio/layout';
import { metadata as metadata35 } from '@/app/(english)/tech/courses/layout';

type MetadataResolver = (props: { params: Record<string, string> }) => Metadata | Promise<Metadata>;
export interface RouteSource {
  pattern: string;
  metadata: MetadataResolver;
  params?: () => Promise<Record<string, string>[]> | Record<string, string>[];
}
export const routeSources: RouteSource[] = [
  { pattern: "/[shortSlug]", metadata: ({ params }) => metadata0({ params: { shortSlug: params["shortSlug"] } }), params: params0 },
  { pattern: "/art-experiences/events/[id]", metadata: ({ params }) => metadata1({ params: { id: params["id"] } }), params: params1 },
  { pattern: "/art-experiences/events", metadata: () => metadata2, params: undefined },
  { pattern: "/art-experiences", metadata: () => metadata3, params: undefined },
  { pattern: "/art-experiences/you-and-i-gallery", metadata: () => metadata4, params: undefined },
  { pattern: "/art/[collection]/[painting]", metadata: ({ params }) => metadata5({ params: { collection: params["collection"], painting: params["painting"] } }), params: params5 },
  { pattern: "/art/[collection]", metadata: ({ params }) => metadata6({ params: { collection: params["collection"] } }), params: params6 },
  { pattern: "/art/about", metadata: () => metadata7, params: undefined },
  { pattern: "/art/all-paintings", metadata: () => metadata8, params: undefined },
  { pattern: "/art/collaborations", metadata: () => metadata9, params: undefined },
  { pattern: "/art/collections", metadata: () => metadata10, params: undefined },
  { pattern: "/art/contact", metadata: () => metadata11, params: undefined },
  { pattern: "/art/early-first-paintings", metadata: () => metadata12, params: undefined },
  { pattern: "/art", metadata: () => metadata13, params: undefined },
  { pattern: "/creative-services/art-classes", metadata: () => metadata14, params: undefined },
  { pattern: "/creative-services/brand-identity", metadata: () => metadata15, params: undefined },
  { pattern: "/creative-services/graphic-recording", metadata: () => metadata16, params: undefined },
  { pattern: "/creative-services", metadata: () => metadata17, params: undefined },
  { pattern: "/creative-services/ux-ui-design", metadata: () => metadata18, params: undefined },
  { pattern: "/my-art/blog", metadata: () => metadata19, params: undefined },
  { pattern: "/my-art/digital-art", metadata: () => metadata20, params: undefined },
  { pattern: "/my-art/everyday-photography", metadata: () => metadata21, params: undefined },
  { pattern: "/my-art/traditional-art", metadata: () => metadata22, params: undefined },
  { pattern: "/my-art/wildlife-photography/gallery", metadata: () => metadata23, params: undefined },
  { pattern: "/my-art/wildlife-photography", metadata: () => metadata24, params: undefined },
  { pattern: "/", metadata: () => baseMetadata, params: undefined },
  { pattern: "/photography/family-maternity/gallery", metadata: () => metadata26, params: undefined },
  { pattern: "/photography/family-maternity", metadata: () => metadata27, params: undefined },
  { pattern: "/photography/headshots/gallery", metadata: () => metadata28, params: undefined },
  { pattern: "/photography/headshots", metadata: () => metadata29, params: undefined },
  { pattern: "/photography/pets/gallery", metadata: () => metadata30, params: undefined },
  { pattern: "/photography/pets", metadata: () => metadata31, params: undefined },
  { pattern: "/photography/wedding-couples/gallery", metadata: () => metadata32, params: undefined },
  { pattern: "/photography/wedding-couples", metadata: () => metadata33, params: undefined },
  { pattern: "/portfolio", metadata: () => metadata34, params: undefined },
  { pattern: "/tech/courses", metadata: () => metadata35, params: undefined },
];
