// Generated by scripts/generate-locale-routes.cjs; edit the English implementation.
export { default } from '@/app/(english)/art-experiences/events/[id]/page';
export { generateStaticParams } from '@/app/(english)/art-experiences/events/[id]/page';
import { metadataForRoute } from '@/i18n/route-metadata';

export async function generateMetadata({ params }: { params: Record<string, string> }) {
  return metadataForRoute("/art-experiences/events/[id]", params, 'es');
}
