// Generated by scripts/generate-locale-routes.cjs; edit the English implementation.
export { default } from '@/app/(english)/creative-services/art-classes/page';
import { metadataForRoute } from '@/i18n/route-metadata';

export async function generateMetadata({ params }: { params: Record<string, string> }) {
  return metadataForRoute("/creative-services/art-classes", params, 'es');
}
